image: microsoft/dotnet:latest
stages:
  - build
  - test
variables:
  test: "EJob.Test"
before_script:
  - "cd EJob"
  - "dotnet restore"
build:
  stage: build
  script:
    - "dotnet build"
test:
  stage: test
  script:
    - "cd $test"
    - "dotnet test"